### ISSUE TITLE
ImportError: Are you sure that uno has been imported?

### ISSUE THREAD

**Issue by sati-bodhi** [Amourspirit/python_ooo_dev_tools#455]
Kept getting this error even though the required package `pyuno` has been installed. 

```
from ooodev.utils.lo import Lo
from ooodev.office.calc import Calc
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[2], line 1
----> 1 from ooodev.utils.lo import Lo
      2 from ooodev.office.calc import Calc

File ~/.pyenv/versions/3.10.6/envs/ydt/lib/python3.10/site-packages/ooodev/utils/lo.py:12
      9 from typing import TYPE_CHECKING, Any, Iterable, Optional, List, Sequence, Tuple, overload, Type, cast
     11 import uno  # pylint: disable=W0611
---> 12 from com.sun.star.beans import XPropertySet  # pylint: disable=E0611
     13 from com.sun.star.frame import XComponentLoader  # noqa E0611
     14 from com.sun.star.frame import XDesktop  # noqa

File ~/.pyenv/versions/3.10.6/envs/ydt/lib/python3.10/site-packages/com/sun/star/__init__.py:11
      7 _IGNORE_IMPORT_ERROR = os.environ.get(
      8     "ooouno_ignore_import_error", None) in ("True", "true", "yes")
     10 if TYPE_CHECKING is False and _IGNORE_IMPORT_ERROR is False:
---> 11     raise ImportError("Are you sure that uno has been imported?")

ImportError: Are you sure that uno has been imported?
```

**Comment by Amourspirit** [comment]
That error is raised by `OooDef` itself. This usually means you virtual environment is not set up correctly.

I am not sure what environment you are using. Please let me know what Operting System you are using. If you are using a virtual environment and any other info that you think may be relevant.

Mean while you can check out the [OooDev Dev Docs](https://python-ooo-dev-tools.readthedocs.io/en/latest/dev_docs/dev_notes.html)

Also I wrote a Python Tools, [oooenv](https://pypi.org/project/oooenv/) That helps configure virtual envoronments for using UNO.

That being said the best way to deveop for LIbreOffice is to use the [Live LibreOffice Python](https://github.com/Amourspirit/live-libreoffice-python) development container if it is possible for you. I is already set to work out of the box, including having LibreOffice installed.

**Comment by sati-bodhi** [comment]
> Please let me know what Operting System you are using. If you are using a virtual environment and any other info that you think may be relevant.

I am using Ubuntu 22.04.3 LTS. I use `pyenv` for my virtual environment.  

[Live LibreOffice Python](https://github.com/Amourspirit/live-libreoffice-python) works like a charm. Thank you!

**Comment by sati-bodhi** [comment]
How do you debug in that environment? Can we use the VScode debugger? Seems like I can only run the script as a macro within LO and debug using the APSO debug extension.

**Comment by sati-bodhi** [comment]
Still getting this error in the container environment...

![Screenshot from 2023-11-24 00-46-45](https://github.com/Amourspirit/python_ooo_dev_tools/assets/7592695/f1cd735e-b244-4d3d-a97b-e47d99c78e9b)

Here is my code: 

```py
# Python Macro for LibreOffice Writer: Find and Replace Text using ooodev
import uno
from ooodev.office.write import Write
from com.sun.star.text import GenericTextDocument

def find_replace_text(replacements):

    xDocument = GenericTextDocument()
    cursor = Write.get_cursor(Write.active_doc)  # type: ignore
    cursor.gotoEnd(False)
    
    # Iterate through each replacement in the dictionary
    for find, replace_text in replacements.items():
        target = "{{" + find + "}}"

        # Reset the cursor to the beginning of the document
        cursor.gotoStart(False)
        
        # Perform find and replace
        xReplaceDescr = xDocument.createReplaceDescriptor()
        xReplaceDescr.setSearchString = target
        xReplaceDescr.setReplaceString = replace_text
        xFound = xDocument.replaceAll( xReplaceDescr )

    
# Define your find and replace dictionary
replacements = {
    "topic": "人口老化",
    "learn": "回答问题",
    # Add more replacements as needed
}

# # Call the find_replace_text function with the current document and replacements
# XSCRIPTCONTEXT = XSCRIPTCONTEXT   # Required for running in LibreOffice
# doc = XSCRIPTCONTEXT.getDocument()
# find_replace_text(doc, replacements)


if __name__ == "__main__":
    find_replace_text(replacements)
```

I should probably use something similar to the code given [here](https://python-ooo-dev-tools.readthedocs.io/en/latest/odev/part2/chapter09.html#replacing-all-the-matching-words).

**Comment by Amourspirit** [comment]
> How do you debug in that environment? Can we use the VScode debugger? Seems like I can only run the script as a macro within LO and debug using the APSO debug extension.

Yes, use Vs Code.
If you run [Live LibreOffice Python UNO Examples](https://github.com/Amourspirit/python-ooouno-ex) container you can see how to debug.

For example to debug the [Hello Save](https://github.com/Amourspirit/python-ooouno-ex/tree/main/ex/auto/writer/odev_hello_save) example do the following.

Open  [start.py](https://github.com/Amourspirit/python-ooouno-ex/blob/main/ex/auto/writer/odev_hello_save/start.py) in VS Code and set a breakpoint.

Now run the code `F5` in debug mode and the breakpoint will work.

**Comment by Amourspirit** [comment]
> Still getting this error in the container environment...
 When calling `OooDev` from a macro make sure you use the [MacroLoader](https://python-ooo-dev-tools.readthedocs.io/en/latest/src/macro/index.html)

**Comment by Amourspirit** [comment]
Also your code example is incorrect.

In the Development Contianer you have access to `loapi`. I fyou run:

```bash
loapi comp -a -s GenericTextDocument
```
You will get:

```
Choose an option (default 1):
[0],  Cancel
[1],  GenericTextDocument               - com.sun.star.text.GenericTextDocument                   - service
```

When you choose an option it will take you to the API webiste for that UNO object (`q` or `esc`) to opt out.
[GenericTextDocument](https://api.libreoffice.org/docs/idl/ref/servicecom_1_1sun_1_1star_1_1text_1_1GenericTextDocument.html) is a service and cannot be imported at runtime. An you can not create an instance of it this way.

Your example should look a little more like this:

```python
# Python Macro for LibreOffice Writer: Find and Replace Text using ooodev
from __future__ import annotations
import uno
from com.sun.star.util import XReplaceable
from com.sun.star.text import XTextDocument
from ooodev.office.write import Write
from ooodev.utils.lo import Lo


def find_replace_text(replacements: dict, doc: XTextDocument):

    # Get the XReplaceable interface from the document
    replaceable = Lo.qi(XReplaceable, doc, True)
    cursor = Write.get_cursor(Wdoc)  # type: ignore
    cursor.gotoEnd(False)
    
    # Iterate through each replacement in the dictionary
    for find, replace_text in replacements.items():
        target = "{{" + find + "}}"

        # Reset the cursor to the beginning of the document
        cursor.gotoStart(False)
        
        # Perform find and replace
        xReplaceDescr = replaceable.createReplaceDescriptor()
        xReplaceDescr.setSearchString = target
        xReplaceDescr.setReplaceString = replace_text
        xFound = replaceable.replaceAll( xReplaceDescr )

    
# Define your find and replace dictionary
replacements = {
    "topic": "人口老化",
    "learn": "回答问题",
    # Add more replacements as needed
}

if __name__ == "__main__":
    # Start LibreOffice Writer and open a document
    with Lo.Loader(Lo.ConnectSocket()) as loader:
        doc = Write.open_doc(fnm="test.odt")
        find_replace_text(replacements, doc)
```

Also note:
use `Lo.xscript_context` or `Lo.XSCRIPTCONTEXT` to access `XSCRIPTCONTEXT` when using `OooDev`

**Comment by Amourspirit** [comment]
See Also the [Text Replace](https://github.com/Amourspirit/python-ooouno-ex/tree/main/ex/auto/writer/odev_text_replace) example.

**Comment by sati-bodhi** [comment]
This code was tested in the docker container and it worked. 

```py
# Python Macro for LibreOffice Writer: Find and Replace Text using ooodev
from __future__ import annotations
import uno
from com.sun.star.util import XReplaceable
from com.sun.star.text import XTextDocument
from ooodev.office.write import Write
from ooodev.utils.lo import Lo
from ooodev.macro import MacroLoader
import os


def find_replace_text(replacements: dict, doc: XTextDocument):

    # Get the XReplaceable interface from the document
    replaceable = Lo.qi(XReplaceable, doc, True)
    cursor = Write.get_cursor(doc)  # type: ignore
    cursor.gotoEnd(False)
    
    # Iterate through each replacement in the dictionary
    for find, replace_text in replacements.items():
        target = "{{" + find + "}}"

        # Reset the cursor to the beginning of the document
        cursor.gotoStart(False)
        
        # Perform find and replace
        xReplaceDescr = replaceable.createReplaceDescriptor()
        xReplaceDescr.setSearchString(target)
        xReplaceDescr.setReplaceString(replace_text)
        xFound = replaceable.replaceAll( xReplaceDescr )

    
# Define your find and replace dictionary
replacements = {
    "topic": "人口老化",
    "learn": "回答问题",
    # Add more replacements as needed
}

if __name__ == "__main__":

    filepath = os.path.join("~/Documents", "test.odt")
    outpath = os.path.join("~/Documents", "out.odt")
    # Start LibreOffice Writer and open a document
    with Lo.Loader(Lo.ConnectSocket()) as loader:
        doc = Write.open_doc(fnm=filepath)
        find_replace_text(replacements, doc)
        Write.save_doc(text_doc=doc, fnm=outpath)

```

But when brought outside, whether in VScode or as a macro in LO, I get errors like these:

![Screenshot from 2023-11-24 11-37-49](https://github.com/Amourspirit/python_ooo_dev_tools/assets/7592695/6fb73a33-e54a-43cb-85cc-f360a3c7f08c)

![Screenshot from 2023-11-24 11-38-14](https://github.com/Amourspirit/python_ooo_dev_tools/assets/7592695/5a589cad-0d06-470c-974e-3835d45f00cc)

**Comment by sati-bodhi** [comment]
I probably need to figure out how to set up the right environment on my own.

**Comment by sati-bodhi** [comment]
> See Also the [Text Replace](https://github.com/Amourspirit/python-ooouno-ex/tree/main/ex/auto/writer/odev_text_replace) example.

This was from the Text Replace example, outside your docker container.

![Screenshot from 2023-11-24 13-11-05](https://github.com/Amourspirit/python_ooo_dev_tools/assets/7592695/8a76f894-31ad-4a6c-b2b8-56fcf08f09f6)

**Comment by sati-bodhi** [comment]
Okay, the code runs when I am in a python environment `/usr/bin/python3` but not when I am in my own specific dev environment.

**Comment by Amourspirit** [comment]
install [oooenv](https://pypi.org/project/oooenv/) into your virtual environment.

Then run:
```bash
oooenv cmd-link -a
```

This will create system links into your virtual environment for `uno.py` and `unohelper.py` which are part of LibreOffice.
