### ISSUE TITLE
ImportError: Are you sure that uno has been imported?

### ISSUE THREAD

**Issue by YouvenZ** [Amourspirit/python_ooo_dev_tools#495]
Thank you for this great piece of work! I facing a small issue here, I have using pip I have installed the ooo_dev_tools package. I have tried to run some basic automation that you have shared in the repo. After the installation, I can import ooo_dev and uno but, however when I call ooodev.utils.lo i have the following error. 
```
 from ooodev.utils.lo import Lo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/youven/anaconda3/envs/ooodevtools/lib/python3.8/site-packages/ooodev/utils/lo.py", line 12, in <module>
    from com.sun.star.beans import XPropertySet  # pylint: disable=E0611
  File "/home/youven/anaconda3/envs/ooodevtools/lib/python3.8/site-packages/com/sun/star/__init__.py", line 11, in <module>
    raise ImportError("Are you sure that uno has been imported?")
ImportError: Are you sure that uno has been imported?
```
Python version:3.8 (I also tried with 3.10) on Ubuntu 22.04.3 LTS  

env detail:
```
Package           Version
----------------- -------
ooo-dev-tools     0.19.0
ooouno            2.1.2
pip               23.3.1
setuptools        68.2.2
types-uno-script  0.1.1
types-unopy       1.2.3
typing_extensions 4.9.0
wheel             0.41.2
```

**Comment by Amourspirit** [comment]
> `ImportError: Are you sure that uno has been imported?`

This is the error that is raised with the virtual environment has not been set up to work with `uno`.

There are a few ways to get around this.

You could install my [oooenv](https://pypi.org/project/oooenv/) package and runs:

```bash
oooenv cmd-link -a
```

This will attempt to find LibreOffice uno files an link them into the virtual enironment on Linux.

A better solution when possible it to create your project from the [Live LibreOffice Python](https://github.com/Amourspirit/live-libreoffice-python) that I put together. I is a Codespace (dev continer) and already has LibreOffice installed with the correct environment to develop a project for LibreOffice UNO (OOO Dev Tools preinstalled)

You can study the [Dev Docs](https://python-ooo-dev-tools.readthedocs.io/en/latest/dev_docs/dev_notes.html) for OooDev that have a lot more info on setting up a virual environment for UNO Development.

Finally you can review the [Pip & Virtual Environments](https://python-ooo-dev-tools.readthedocs.io/en/latest/guide/virtual_env/index.html) guides.

**Comment by YouvenZ** [comment]
I tried the first recommendation and now i can do the following cmd
```
oooenv cmd-link -a

```
 and the import works now. Thank you a lot👍🏽. I definitely will take a look to [Live LibreOffice Python](https://github.com/Amourspirit/live-libreoffice-python) since I am trying to automate many workflows it will be quite handy. Once again thanks for the amazing work around Lo.
I will close the issue

**Comment by JulienPalard** [comment]
Creating the venv with `--system-site-packages` helped me here.
