### ISSUE TITLE
[question] How to save document impress/draw directly on the go

### ISSUE THREAD

**Issue by YouvenZ** [Amourspirit/python_ooo_dev_tools#498]
I have tested many examples in the auto folder. They are well-documented and easy to understand.

In the provided example in the auto folder, I would generally like to generate a document and save the document (of any type: Calc, Writer, Impress, or Draw). For the Writer API and the Calc, you provided an example that demonstrates how to do this. I tried to find an example for Draw/Impress but did not find.

I have tried to directly save (as slides .odp or .ppt) the object doc. I have tried the following with your example `PointsBuilder`:
```
class PointsBuilder:
    def __init__(self, points_fnm: PathOrStr) -> None:
        if not FileIO.is_exist_file(fnm=points_fnm, raise_err=True):
            raise FileNotFoundError(f"File not found: {points_fnm}")
        self._points_fnm = FileIO.get_absolute_path(points_fnm)

    def main(self) -> None:
        loader = Lo.load_office(Lo.ConnectSocket(headless=True))  # Change to headless

        # Create Impress page or Draw slide
        try:
            self._report_templates()
            tmpl_name = "Inspiration.otp"  # "Piano.otp"
            template_fnm = Path(Draw.get_slide_template_path(), tmpl_name)
            if not FileIO.is_exist_file(template_fnm):
                raise FileNotFoundError(f"File not found: {template_fnm}")
            doc = ImpressDoc(
                Lo.create_doc_from_template(template_path=template_fnm, loader=loader)
            )

            self._read_points(doc)

            # Tried to save
            save_file_url = FileIO.fnm_to_url("./example.odp")
            store_props = Props.make_props(Overwrite=True, FilterName="odp")

            # The following line raises an `XStorage` exception
            # store = Lo.qi(XStorable, doc)
            # Lo.save_doc(doc, "./example.odp")  # The rest is the same

        except Exception as e:
            print(f"Error during save: {e}")
```

I am still getting the `XStorage` exception. Could you please provide an example or some guidance on this matter?

**Comment by Amourspirit** [comment]
Because `doc` is a `ImpressDoc` class you need to access the component object that `ImpressDoc` wraps.

Simply put use `doc.component` when saving with Lo. `Lo.save_doc(doc.component, "./example.odp")`

On the next realease of `OooDev ` (0.20.2`) I will include a save doc on the ImpressDoc class so then you can `doc.save_doc(".example.odp").

**Comment by Amourspirit** [comment]
[OOO Development Tools](https://pypi.org/project/ooo-dev-tools/) 0.20.2 just released. Now has a `save_doc()` method for `ImpressDoc`

[Points builder](https://github.com/Amourspirit/python-ooouno-ex/tree/main/ex/auto/impress/odev_points_builder) example has been updated to include a save option for demo purposes.

If you using [extension](https://extensions.libreoffice.org/en/extensions/show/41700) then Update you extension in LibreOffice using the Extension Manager.
