### ISSUE TITLE
need help creating dialog

### ISSUE THREAD

**Issue by scenaristeur** [Amourspirit/python_ooo_dev_tools#566]
Hi nice job, 
Could you please give me an example to create Dialog with text input, slider... 
thxs

**Comment by Amourspirit** [comment]
@scenaristeur [Checkout Dialog Examples](https://github.com/Amourspirit/python-ooouno-ex/tree/main/ex/dialog) on [Live LibreOffice Python UNO Examples](https://github.com/Amourspirit/python-ooouno-ex/tree/main)
