### ISSUE TITLE
Frozen rows and columns losts on save

### ISSUE THREAD

**Issue by JulienPalard** [Amourspirit/python_ooo_dev_tools#580]
Hi!

First thanks for the lib and documentation, I feared UNO, you made it usable for my simple case, I'm very happy using:

```python
        with Lo.Loader(Lo.ConnectSocket(headless=True)) as loader:
            doc = Lo.open_doc(fnm=args.to_ods, loader=loader)
            calc = CalcDoc(doc)
            sheet = calc.sheets["Ma Sheet"]
```

followed by a few `sheet[(column_idx, row)].set_val(`, it just works as expected, wow.

But one thing is still frustrating: when I `Calc.save_doc(doc, args.to_ods)` and open the doc back with LibreOffice 24.2.0.3 to see it on Debian Trixie, the previously frozen column and frozen row are now unfrozen, I have to refreeze them every time.

I bet that's not even an issue in this lib, sorry if it's the case...

**Comment by Amourspirit** [comment]
This is not an issue with this library.
I tested this with [Calc Add Range of Data Automation](https://github.com/Amourspirit/python-ooouno-ex/tree/main/ex/auto/calc/odev_add_range_data) on Ubuntu 22.04 and in Development container. I froze the first row and saved the doc in LibreOffice 7.6. I open the doc in LibreOffice 2024.2 and the frozen row was fine.

BTW you can also open Calc doc this way.

```pyhhon
calc = CalcDoc.open_doc(fnm=self._fnm)
```
