### ISSUE TITLE
Interface with Base

### ISSUE THREAD

**Issue by PierreDeQuebec** [Amourspirit/python_ooo_dev_tools#655]
I naively tried to run the "Hello World" example from Base. It doesn't work. I understood that the interface to Base was not implemented yet and that I could not invoke code that retrieves an open Base DB using Lo.current_doc. Question: is the implementation of the interface to Base coming soon?

**Comment by Amourspirit** [comment]
Base is a huge implementation. It has been on my mind for some time. I intend to create the modules for Base.
Not entirely sure if it will be part of `ooodev` directly or if it will be a separate package just yet.

This is a matter of time and resources for me. As if right now the Base module is not yet started. My current aim is to get something out for 2025, any luck in the spring.
If anyone wants to contribute to this project it would be welcomed and perhaps this could move forward more quickly.
