### ISSUE TITLE
Strange logic while killing ooo

### ISSUE THREAD

**Issue by JulienPalard** [Amourspirit/python_ooo_dev_tools#666]
I'm using:

        with Lo.Loader(Lo.ConnectSocket(headless=True)) as loader:

a lot, and I noticed it won't kill ooo. That's not really an issue until I try to open a real ooo for my personal use...

After reading the code I find it strange, in `ooodev/loader/inst/lo_inst.py` I see:

```python
    def close_office(self) -> bool:
[,,,]
        self.on_office_closing(cargs)
[...]
            self._is_office_terminated = self._try_to_terminate(num_tries)
```

but `on_office_closing` is setting `self._xdesktop = None` and `try_to_terminate` starts with `if self._xdesktop is None: return True`, so it does nothing ☹

**Comment by Amourspirit** [comment]
Excellent Catch! Thanks for reporting this.
Version `0.47.18` is now published and this issue has been fixed.
Again Thank you.
