### ISSUE TITLE
Include Code Files in Docs as Single Source

### ISSUE THREAD

**Issue by flywire** [Amourspirit/python_ooo_dev_tools#73]
https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#showing-code-examples

**Comment by Amourspirit** [comment]
What do you have in mind here?
Docs currently use code-block:: to display many example ( with tabs often to state language such as basic, python )

**Comment by flywire** [comment]
I may have the wrong understanding. I saw [code blocks in rst files](https://github.com/Amourspirit/python_ooo_dev_tools/blame/main/docs/odev/part1/chapter01.rst#L528-L556) but later noticed code files are included from original source. If it is not an issue then close it.
