### ISSUE TITLE
Check Spelling as Docs Developed

### ISSUE THREAD

**Issue by flywire** [Amourspirit/python_ooo_dev_tools#74]
eg: https://sphinxcontrib-spelling.readthedocs.io/en/latest/index.html

**Comment by flywire** [comment]
```
(.venv) E:\SOURCE\repos\python_ooo_dev_tools\docs>sphinx-build -b spelling . _build
...
Looking for custom word list in ...python_ooo_dev_tools\docs\spelling_wordlist.txt
...
WARNING: Found 615 misspelled words
build succeeded, 1 warning.
```

It's a mix between unrecognised and wrong.

**Comment by flywire** [comment]
Seems an oxymoron to have typos in a type-checking app.

Some of the remaining typos are so deeply nested in rst files they are nearly impossible to find. The real concern is typos in code logic with the real solution being to produce documents without typos. I run a spell checker in np++, LibreOffice, and Brave so typos are fixed as documents are written.

**Comment by Amourspirit** [comment]
I have merged the spelling correction ( into develop branch).
What other specific suggestion do you have for this issue?

BTW: please direct any pull request to development branch.

**Comment by flywire** [comment]
> Looking for custom word list in ...python_ooo_dev_tools\docs\spelling_wordlist.txt

Needs creating.

No other suggestions. Even with that extension it will be much easier to fix typos as you go. The spell check interface is very similar to type-checking. 

Can you do a `Contributions` page? I understand you want feature branch -> development branch -> main branch. I suppose this means you will ensure normally development branch = main branch. Is it just a matter of changing where the pull request is directed or do I need to base the pull request on my fork of the development branch?

**Comment by flywire** [comment]
Get words not found in Win with gnu sed: `sed -n 's/.*check: \(.*\):.*/\1/p'`

Make a unique list, extract know words and add to _...python_ooo_dev_tools\docs\spelling_wordlist.txt_
