### ISSUE TITLE
Configure Sphinx for Offline Use

### ISSUE THREAD

**Issue by flywire** [Amourspirit/python_ooo_dev_tools#75]
1. Ensure docs updated on local server when changed eg https://github.com/codesmythe/gnucash-docs-rst/commit/bdf1db776bf298893edb8a08473c443accb0c148
1. Developer docs, eg https://github.com/codesmythe/gnucash-docs-rst/blob/master/source/Host%20this%20Locally.md

**Comment by flywire** [comment]
Seems `livehtml` is outdated: https://pypi.org/project/sphinx-autobuild/

**Comment by Amourspirit** [comment]
Building and view docs on local host is already set up on project.

Create a new terminal window to run http server.
Run: `python .\cmds\run_http.py`
That creates starts a local webserver

Create a new terminal windows for building docs.
`cd docs`
to make `.\make.bat html`
to clear so all can be forced  to make again ` .\make.bat clear`


https://user-images.githubusercontent.com/4193389/180458381-87e5aee0-d688-496b-a5a7-b2db8d430cfe.mp4

**Comment by Amourspirit** [comment]
Oh, http://localhost:8000/docs/_build/html/index.html to view docs once local http server is started.

**Comment by flywire** [comment]
You missed the point. None of that was required with `livehtml`. User just saved the file and the display was updated in the browser at 8000, like a delayed WYSIWYG. I assume [sphinx-autobuild/](https://pypi.org/project/sphinx-autobuild/) does the same.
